
# Cell States
CELL_EMPTY   = 0
CELL_FILLED  = 1
CELL_CROSSED = 2

# Clue States
CLUE_UNSOLVED = 0
CLUE_PARTIAL  = 1
CLUE_SOLVED   = 2

# Diagnosis Values
DIAG_ERROR        = -1
DIAG_NONE         = 0
DIAG_DELETE       = 1
DIAG_LINESOLVED   = 2
DIAG_SEGSOLVABLE  = 3
